In [32]:
import pandas as pd
import requests

In [33]:
url = "https://tld-list.com/df/tld-list-details.json"

In [34]:
response = requests.get(url)
json_response = response.json()

df = pd.DataFrame.from_dict(json_response)
tld_df = df.transpose()

tld_df

,type,punycode,language_code,translation,romanized,rtl,sponsor
aaa,gTLD,None,None,None,None,False,"American Automobile Association, Inc."
aarp,gTLD,None,None,None,None,False,AARP
abarth,gTLD,None,None,None,None,False,Fiat Chrysler Automobiles N.V.
abb,gTLD,None,None,None,None,False,ABB Ltd
abbott,gTLD,None,None,None,None,False,"Abbott Laboratories, Inc."
...,...,...,...,...,...,...,...
닷넷,gTLD,xn--t60b56a,ko,net,datnet,False,VeriSign Sarl
닷컴,gTLD,xn--mk1bu44c,ko,dotcom,datkeom,False,VeriSign Sarl
삼성,gTLD,xn--cg4bki,ko,samsung,None,False,"SAMSUNG SDS CO., LTD"
테스트,test,xn--9t4b11yi5a,ko,test,teseuteu,False,Internet Assigned Numbers Authority
한국,ccTLD,xn--3e0b707e,ko,republic of korea,None,False,KISA (Korea Internet & Security Agency)